swagger: '2.0'
info:
  version: 1.0.0
  title: TomoStats APIs
  description: Happy to code TomoStats APIs
  license:
    name: Github
    url: 'https://github.com/tomochain/tomostats'
tags:
  - name: Config
    description: Get TomoStats Application Configuration
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/config:
    get:
      tags:
        - Config
      summary: Get TomoStats Application Configuration
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Server Internal Error